IthsLetsEatFastFood/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using IthsLetsEatFastFood.Models;
using IthsLetsEatFastFood.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using IthsLetsEatFastFood.Services.ChangeService;

namespace IthsLetsEatFastFood.Controllers
{
    public class CartController : Controller
    {
       
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOrderService _orderService;
        

        private const string sessionKeyCart = "_cart";

        public CartController( UserManager<ApplicationUser> userManager, IOrderService orderService)
        {
           _userManager = userManager;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var cart = HttpContext.Session.Get<List<CartItem>>(sessionKeyCart);
                        

            CartViewModel vm= new CartViewModel();
            vm.FoodProducts = cart;

            vm.TotalPrice = vm.FoodProducts.Sum(fp => fp.FoodProduct.Price * fp.Amount);

            return View(vm);
        }

        public IActionResult Delete(Guid id)
        {
            var cart = HttpContext.Session.Get<List<CartItem>>(sessionKeyCart).ToList();
            if (cart != null)
            {
                HttpContext.Session.Remove(sessionKeyCart);
                HttpContext.Session.Set(sessionKeyCart, cart.Where(x => x.FoodProduct.Id != id));               
            }            
            return RedirectToAction("Index");

        }
        
        public async Task<IActionResult> MyOrder([Bind("TotalPrice, FoodProduct")] CartViewModel cart)
        {
            cart.FoodProducts = HttpContext.Session.Get<List<CartItem>>(sessionKeyCart);
            OrderViewModel viewModel = new OrderViewModel();
            Order order = new Order();
            order.Date = DateTime.Now;
            order.TotalPrice = cart.TotalPrice;
            order.OrderRows = cart.FoodProducts.Select(cartItem => new OrderRow(cartItem)
            {
                Amount = cartItem.Amount,
                FoodProduct = cartItem.FoodProduct
            }).ToList();
            var userIdentity = User.FindFirstValue(ClaimTypes.NameIdentifier);
            order.UserId = Guid.Parse(_userManager.GetUserId(User));

            viewModel.Order = order;
            var user = await _userManager.GetUserAsync(User);
            viewModel.User = user;

            //save to the database through order service
            _orderService.SaveOrder(cart);

           return View("OrderSuccess", viewModel);
        }

        public IActionResult OrderSuccess(Order order)
        {
            return View(order);
        }


    }
   
}

IthsLetsEatFastFood/Controllers/FoodProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using IthsLetsEatFastFood.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using IthsLetsEatFastFood.ViewModel;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using IthsLetsEatFastFood.Services.QueryService;

namespace IthsLetsEatFastFood.Controllers
{
    public class FoodProductController : Controller
    {
        
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IQueryService _queryService;

        private const string sessionKeyCart = "_cart";
        private const string sessionKeyUserId = "_userId";

        public FoodProductController(UserManager<ApplicationUser> userManager, IQueryService queryService)
        {
            _userManager = userManager;
            _queryService = queryService;
        }


        public IActionResult Index()
        {
            return View(_queryService.GetProductList());                    
        }
 
       [Authorize]
        public IActionResult AddToCart(Guid id)
        {
           

            var currentCartItems = HttpContext.Session.Get<List<CartItem>>(sessionKeyCart);
            var userSessionId = HttpContext.Session.Get<Guid>(sessionKeyUserId);
            var actualUserId = Guid.Parse(_userManager.GetUserId(User));         

            List<CartItem> cartItems = new List<CartItem>();

            
            if (currentCartItems != null)
            {
                cartItems = currentCartItems;
                if (userSessionId != actualUserId)
                {
                    currentCartItems = null;
                    HttpContext.Session.Clear();
                    cartItems = new List<CartItem>();

                }

                HttpContext.Session.Set<Guid>(sessionKeyUserId, actualUserId);
              
            }
            if (currentCartItems != null && currentCartItems.Any(fp => fp.FoodProduct.Id == id))
            {
                int foodProductIndex = currentCartItems.FindIndex(fp => fp.FoodProduct.Id == id);
                currentCartItems[foodProductIndex].Amount += 1;
                cartItems = currentCartItems;
            }
            else
            {
                var foodProduct = _queryService.GetProductById(id);
                CartItem newCartItem = new CartItem()
                {
                    FoodProduct = new Models.FoodProduct {
                        Id=foodProduct.Id,
                        Description=foodProduct.Description,
                        ImageUrl=foodProduct.ImageUrl,
                        Name=foodProduct.Name,
                        Price=(decimal)foodProduct.Price
                    },
                    Amount = 1
                };
                cartItems.Add(newCartItem);
            }
            
            HttpContext.Session.Set<List<CartItem>>(sessionKeyCart, cartItems);

            // _foodService.AddToCart(newCartItem);
            return RedirectToAction("Index");
        }


    }


    // "https://www.c-sharpcorner.com/article/session-state-in-asp-net-core-and-mvc-core/"
    public static class SessionExtensions
    {
        public static void Set<T>(this ISession session, string key, T value)
        {
            session.SetString(key, JsonConvert.SerializeObject(value));
        }

        public static T Get<T>(this ISession session, string key)
        {
            var value = session.GetString(key);
            return value == null ? default :
                                  JsonConvert.DeserializeObject<T>(value);
        }
    }
}

IthsLetsEatFastFood/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IthsLetsEatFastFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/foodProdu.css" />
    

</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light border-bottom box-shadow mb-3">

            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IthsLetsEatFastFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart  <span id="cart-amount"></span></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FoodProduct" asp-action="Index">FoodProduct</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Samrawit Haylemeskel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Learn more</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/cart.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>